/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas.praktikum.pkg07.pkg08;

/**
 *
 * @author ACER NITRO
 */
public class PenentuJumlahHari extends javax.swing.JFrame {
 
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName());
 
    // Nama-nama bulan (index 0 = Januari)
    private static final String[] NAMA_BULAN = {
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    };
 
    public PenentuJumlahHari() {
        initComponents();
        bindActions();
    }
 
    // ── Pasang semua listener ─────────────────────────────────────────────────
    private void bindActions() {
 
        // Hitung
        buttonHitung.addActionListener(e -> hitungHari());
 
        // Hapus
        buttonHapus.addActionListener(e -> {
            inputTahun.setText("");
            boxBulan.setSelectedIndex(0);
            labelOutput.setText("");
            inputTahun.requestFocus();
        });
 
        // Simpan ke file .txt
        buttonSimpan.addActionListener(e -> simpanHasil());
 
        // Keluar dengan konfirmasi
        buttonKeluar.addActionListener(e -> {
            int reply = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Yakin ingin keluar?",
                    "Konfirmasi Keluar Aplikasi",
                    javax.swing.JOptionPane.YES_NO_OPTION);
            if (reply == javax.swing.JOptionPane.YES_OPTION) {
                System.exit(0);
            } else {
                inputTahun.requestFocus();
            }
        });
    }
 
    // ── Logika Hitung ─────────────────────────────────────────────────────────
    private void hitungHari() {
        String teksT = inputTahun.getText().trim();
 
        if (teksT.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this, "Tahun tidak boleh kosong!", "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            inputTahun.requestFocus();
            return;
        }
 
        int tahun;
        try {
            tahun = Integer.parseInt(teksT);
            if (tahun <= 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this, "Masukkan tahun yang valid (bilangan bulat positif)!",
                    "Input Salah", javax.swing.JOptionPane.ERROR_MESSAGE);
            inputTahun.requestFocus();
            return;
        }
 
        int indexBulan = boxBulan.getSelectedIndex(); // 0-based
        int nomorBulan = indexBulan + 1;              // 1-based
        String namaBulan = NAMA_BULAN[indexBulan];
 
        // Panggil class HitungHari
        HitungHari hh = new HitungHari(tahun, nomorBulan);
        int jumlahHari = hh.hitung();
 
        labelOutput.setText(
                "Jumlah hari pada bulan " + namaBulan +
                " tahun " + tahun + " adalah " + jumlahHari);
    }
 
    // ── Simpan ke file .txt ───────────────────────────────────────────────────
    private void simpanHasil() {
        String hasilTeks = labelOutput.getText().trim();
 
        if (hasilTeks.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this, "Belum ada hasil yang bisa disimpan!\nTekan Hitung terlebih dahulu.",
                    "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        try (java.io.BufferedWriter out = new java.io.BufferedWriter(
                new java.io.FileWriter("jumlahhari.txt"))) {
            out.write(hasilTeks);
            out.newLine();
            javax.swing.JOptionPane.showMessageDialog(
                    this, "Berhasil disimpan dalam file 'jumlahhari.txt'",
                    "Simpan", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this, "Gagal menyimpan file: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAplikasi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTahun = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        inputTahun = new javax.swing.JTextField();
        boxBulan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        labelOutput = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonHitung = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelAplikasi.setBackground(new java.awt.Color(255, 255, 255));
        labelAplikasi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelAplikasi.setForeground(new java.awt.Color(0, 0, 0));
        labelAplikasi.setText("Aplikasi Penentu Jumlah Hari");

        jPanel2.setBackground(new java.awt.Color(102, 204, 0));

        labelTahun.setBackground(new java.awt.Color(255, 255, 255));
        labelTahun.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelTahun.setForeground(new java.awt.Color(0, 0, 0));
        labelTahun.setText("Tahun");

        labelBulan.setBackground(new java.awt.Color(255, 255, 255));
        labelBulan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelBulan.setForeground(new java.awt.Color(0, 0, 0));
        labelBulan.setText("Bulan");

        inputTahun.setBackground(new java.awt.Color(255, 255, 255));
        inputTahun.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        inputTahun.setForeground(new java.awt.Color(51, 51, 51));

        boxBulan.setBackground(new java.awt.Color(255, 255, 255));
        boxBulan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boxBulan.setForeground(new java.awt.Color(0, 0, 0));
        boxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        boxBulan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                boxBulanComponentShown(evt);
            }
        });
        boxBulan.addActionListener(this::boxBulanActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBulan)
                    .addComponent(labelTahun))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxBulan, 0, 196, Short.MAX_VALUE)
                    .addComponent(inputTahun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTahun)
                    .addComponent(inputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBulan)
                    .addComponent(boxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        labelOutput.setBackground(new java.awt.Color(255, 255, 255));
        labelOutput.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        buttonHitung.setBackground(new java.awt.Color(51, 153, 255));
        buttonHitung.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        buttonHitung.setForeground(new java.awt.Color(0, 0, 0));
        buttonHitung.setText("Hitung");

        buttonHapus.setBackground(new java.awt.Color(51, 153, 255));
        buttonHapus.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(0, 0, 0));
        buttonHapus.setText("Hapus");

        buttonSimpan.setBackground(new java.awt.Color(51, 153, 255));
        buttonSimpan.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(0, 0, 0));
        buttonSimpan.setText("Simpan");

        buttonKeluar.setBackground(new java.awt.Color(51, 153, 255));
        buttonKeluar.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        buttonKeluar.setForeground(new java.awt.Color(0, 0, 0));
        buttonKeluar.setText("Keluar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(buttonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonKeluar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHitung)
                    .addComponent(buttonHapus)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonKeluar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAplikasi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBulanActionPerformed

    private void boxBulanComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_boxBulanComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBulanComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new PenentuJumlahHari().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxBulan;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JTextField inputTahun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAplikasi;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelOutput;
    private javax.swing.JLabel labelTahun;
    // End of variables declaration//GEN-END:variables
}
